services:
  ################################
  # API Gateway Service
  ################################

  api-gateway:
    ports:
      - '4000:3000'
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile 
    image: api-gateway:prod 
    container_name: api-gateway-prod
    restart: unless-stopped
    env_file:
    - ./services/api-gateway/.env

    networks:
      - microservices_network_production

################################
# Networks
################################
networks:
  microservices_network_production:
    driver: bridge
  