services:
  ################################
  # API Gateway Service
  ################################

  api-gateway:
    ports:
      - '4000:3000'
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile 
    image: api-gateway:prod 
    container_name: api-gateway-prod
    restart: unless-stopped
    env_file:
    - ./services/api-gateway/.env

    networks:
      - microservices_network_production

  ################################
  # RabbitMQ (Shared Messaging)
  ################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-prod
    restart: unless-stopped
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
  environment:
    RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}      
        
    networks:
      - microservices_network_production

################################
# Networks
################################
networks:
  microservices_network_production:
    driver: bridge
  