name: ecommerce-dev
services:
  ################################
  # RabbitMQ (Shared Messaging)
  ################################
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    restart: unless-stopped
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    env_file:
      - .env.dev
    networks:
      - microservices_network
      
  ################################
  # API Gateway Service
  ################################

  api-gateway:
    ports:
      - '${HOST_PORT:-3000}:3000'
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    image: api-gateway:dev
    container_name: api-gateway-dev
    restart: unless-stopped
    env_file:
      - ./services/api-gateway/.env.dev
    networks:
      - microservices_network

  ################################
  # Identity Service
  ################################
  identity-service:
    ports:
      - '${HOST_PORT:-3001}:3001'
    build:
      context: ./services/identity-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/identity-service:/app
      - /app/node_modules
    image: identity-service:dev
    container_name: identity-service-dev
    restart: unless-stopped
    environment:
      NODE_ENV: dev
    env_file:
      - ./services/identity-service/.env.dev
    networks:
      - microservices_network      
    

  ################################
  # Identity Database
  ################################
  identity-db:
    image: postgres:16
    container_name: identity-db-dev
    restart: unless-stopped
    env_file:
      - ./services/identity-service/.env.dev
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    networks:
      - microservices_network

  ################################
  # Email Worker Service
  ################################

  email-worker:
    image: email-worker:dev
    container_name: email-worker-dev
    build:
      context: ./services/email-worker
      dockerfile: Dockerfile.dev
    env_file:
      - ./services/email-worker/.env.dev

    volumes:
      - ./services/email-worker:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - microservices_network

  ################################
  # Catalog Service
  ################################
  catalog-service:
    ports:
      - '${HOST_PORT:-3002}:3002'
    build:
      context: ./services/catalog-service
      dockerfile: Dockerfile.dev
    image: catalog-service:dev  
    container_name: catalog-service-dev
    restart: unless-stopped
    env_file:
      - ./services/catalog-service/.env.dev
    volumes:
      - ./services/catalog-service:/app
      - /app/node_modules
    networks:
      - microservices_network

  ################################
  # Catalog Database
  ################################
  catalog-db:
    image: postgres:16
    container_name: catalog-db-dev
    restart: unless-stopped
    env_file:
      - ./services/catalog-service/.env.dev
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5434}:5432'
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
    networks:
      - microservices_network   

  ################################
  # Order Service
  ################################
  order-service:
    ports:
      - '${HOST_PORT:-3003}:3003'
    build:
      context: ./services/order-service
      dockerfile: Dockerfile.dev
    image: order-service:dev  
    container_name: order-service-dev
    restart: unless-stopped
    env_file:
      - ./services/order-service/.env.dev
    volumes:
      - ./services/order-service:/app
      - /app/node_modules
    networks:
      - microservices_network   

  ################################
  # Order Database
  ################################
  order-db:
    image: postgres:16
    container_name: order-db-dev
    restart: unless-stopped
    env_file:
      - ./services/order-service/.env.dev
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5435}:5432'
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - microservices_network               

################################
# Networks
################################
networks:
  microservices_network:
    driver: bridge

################################
# Volumes
################################
volumes:
  identity_db_data:
  catalog_db_data:
  payment_db_data:
  order_db_data:
  identity_test_db_data:
